a=input("Enter the first number:")
b=input("Enter the second number:")
c=int(a)+int(b)
d=int(a)-int(b)
e=int(a)*int(b)
f=int(a)/int(b)
print("addition:",c)
print("substraction:",d)
print("multiplication:",e)
print("divison:",f)

